### ISSUE TITLE
Scale starts two threads. But why?

### ISSUE THREAD

**Issue by karlTGA** [gewv-tu-dresden/vosekast_control#13]
I dont understand, why the scale module starts two threads. What is the task of each thread and is it possible to combine the threads in one?

**Comment by immunity-anomaly** [comment]
thread_loop gets timestamp and scale value from read_value_from_scale and the sleeps for 1 second.
thread_readscale is a workaround to get the newest value from the scale which then gets passed on to read_value_from_scale. It gets the value every 50ms to make sure to always have the most current value.

**Comment by karlTGA** [comment]
aha I remember. That was a problem with the serial buffer. I think you should combine the threads. Maybe if you clear the buffer and call then readline. Readline blocks until a lineending was written.

**Comment by immunity-anomaly** [comment]
I tried clearing the buffer and then calling readline before. That cause some problems, therefore I created _scale_input_buffer (thread_readscale).

Are there any downsides to having two separate threads?

**Comment by karlTGA** [comment]
In my opinion it produce unnecessary overhead. Threads to handle is every time complicated.  If you can you should avoid it.
