### ISSUE TITLE
Scale method add_new_value should add the value to the history

### ISSUE THREAD

**Issue by karlTGA** [gewv-tu-dresden/vosekast_control#16]
https://github.com/gewv-tu-dresden/vosekast_control/blob/84e4ee52bcf459f3c0fe79d9e5e6328725c1d756/vosekast_control/Scale.py#L96

**Comment by immunity-anomaly** [comment]
adressed in https://github.com/gewv-tu-dresden/vosekast_control/commit/b00117abcf6866fb0bf8e7ec357653dffd0fb765

**Comment by karlTGA** [comment]
I dont see the fix in b00117a

**Comment by immunity-anomaly** [comment]
sorry, please see commit https://github.com/gewv-tu-dresden/vosekast_control/commit/65d0169530d82e69ea6dd89a480c9c33ca0f0000

**Comment by karlTGA** [comment]
Ah ok. Fine.
