### ISSUE TITLE
Use @property getter to change a property

### ISSUE THREAD

**Issue by karlTGA** [gewv-tu-dresden/vosekast_control#4]
https://github.com/gewv-tu-dresden/vosekast_control/blob/611d1ea51d444a5e9974238e6d3e4d8dce0be1c0/vosekast_control/Tank.py#L119

Getter should only get values. That is a really weird code snippet.

**Comment by immunity-anomaly** [comment]
fixed in branch issue4

**Comment by immunity-anomaly** [comment]
fixed, please see pull request
