### ISSUE TITLE
Vosekast should send healthy messages over mqtt

### ISSUE THREAD

**Issue by karlTGA** [gewv-tu-dresden/vosekast_control#6]
So that a client knows whether the Vosekast is running, it should send healty messages at regular intervals. 

Example Implementation MQTT.py:
``` python
def on_connect(self, client, flags, rc, properties):
        self.client.subscribe(self.topic, qos=0)
        self.logger.debug('Connected to host: \"' + self.host + "\"")
        self._start_healthy_loop()

async def _start_healthy_loop(self):
        while self.connected:
             self.publish_message(StatusMessage('system', 'healthy')
             await asyncio.sleep(10)
```

**Comment by immunity-anomaly** [comment]
System displays "RuntimeWarning: coroutine 'MQTTController.on_connect' was never awaited self.on_connect(self, flags, result, self.properties)".
Is there a way to do this if gmqtt does not await on_connect?
