### ISSUE TITLE
Init MQTT and DB Client in seperate File and import only the instance

### ISSUE THREAD

**Issue by karlTGA** [gewv-tu-dresden/vosekast_control#7]
You can init classes in the same file. For example:
``` python 
class A:
    def __init__(self):
        self.foo = 12

instance_of_a = A()
```

In other files you can import the instance, not the class:
``` python
from A import instance_of_a

print(instance_of_a.foo)
```

python run the class init only once and gives you everytime the same instance back. So you can connect your clients in one place and simply share that. That prevent the the sharing over parameters.

**Comment by karlTGA** [comment]
This concept is called singletons. 
https://de.wikipedia.org/wiki/Singleton_(Entwurfsmuster)

**Comment by immunity-anomaly** [comment]
addressed in https://github.com/gewv-tu-dresden/vosekast_control/commit/68d5f0944c95c5d091e5aa6b897629575f9a903f and https://github.com/gewv-tu-dresden/vosekast_control/commit/9471a3183891bc0f3db49e13c77a18c415709cf6
